services:
  - type: web
    name: cauri-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CINETPAY_APIKEY
        sync: false
      - key: CINETPAY_SITE_ID
        sync: false
      - key: CINETPAY_TRANSFER_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: OWNER_MOMO_PREFIX
        value: "229"
      - key: OWNER_MOMO_PHONE
        value: "0162552778"
